// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDKqk02W8iHpSX0Z86r7yJpE6fFzkRW8',
    appId: '1:471194165642:web:154854e7850c179c9aa873',
    messagingSenderId: '471194165642',
    projectId: 'sesan-travel',
    authDomain: 'sesan-travel.firebaseapp.com',
    storageBucket: 'sesan-travel.firebasestorage.app',
    measurementId: 'G-0BBJYM6ZP3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpvsdnT-4ukswqCOrn-YCM8qWRfP0xp8Q',
    appId: '1:471194165642:ios:267463eab9e2d9979aa873',
    messagingSenderId: '471194165642',
    projectId: 'sesan-travel',
    storageBucket: 'sesan-travel.firebasestorage.app',
    iosBundleId: 'com.example.sesanTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDKqk02W8iHpSX0Z86r7yJpE6fFzkRW8',
    appId: '1:471194165642:web:679e1f759e26f6ec9aa873',
    messagingSenderId: '471194165642',
    projectId: 'sesan-travel',
    authDomain: 'sesan-travel.firebaseapp.com',
    storageBucket: 'sesan-travel.firebasestorage.app',
    measurementId: 'G-8TBP5NXDNM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpvsdnT-4ukswqCOrn-YCM8qWRfP0xp8Q',
    appId: '1:471194165642:ios:267463eab9e2d9979aa873',
    messagingSenderId: '471194165642',
    projectId: 'sesan-travel',
    storageBucket: 'sesan-travel.firebasestorage.app',
    iosBundleId: 'com.example.sesanTravel',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBkQNHxShMuSLRrYpJI7PMcWaYJkVsvk',
    appId: '1:471194165642:android:274a246df1241f079aa873',
    messagingSenderId: '471194165642',
    projectId: 'sesan-travel',
    storageBucket: 'sesan-travel.firebasestorage.app',
  );
}
